### ISSUE TITLE
Modificar checkbox de filtros

### ISSUE THREAD

**Issue by thayannevls** [analytics-ufcg/leggo-frontend#217]
Atualmente todos os checkbox começam marcados, quando o usuário precisa filtrar por algo, ele precisa desmarcar todas as outras o que não é um padrão comum

Ideal é ser parecido como o desse [site](https://www.booking.com/searchresults.en-us.html?aid=397594&label=gog235jc-1DCAEoggI46AdIM1gDaCCIAQGYATG4ARnIAQzYAQPoAQH4AQKIAgGoAgM&sid=987a24a1186caab609ae977b42071972&sb=1&src=index&src_elem=sb&error_url=https%3A%2F%2Fwww.booking.com%2Findex.html%3Faid%3D397594%3Blabel%3Dgog235jc-1DCAEoggI46AdIM1gDaCCIAQGYATG4ARnIAQzYAQPoAQH4AQKIAgGoAgM%3Bsid%3D987a24a1186caab609ae977b42071972%3Bsb_price_type%3Dtotal%26%3B&ss=sao+paulo&is_ski_area=0&checkin_month=&checkin_monthday=&checkin_year=&checkout_month=&checkout_monthday=&checkout_year=&group_adults=2&group_children=0&no_rooms=1&b_h4u_keep_filters=&from_sf=1)

**Comment by tarcisocomp** [comment]
Resolvido em #241
