### ISSUE TITLE
Eventos duplicados

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/leggo-frontend#234]
Exemplo: Escola sem Partido. Os dois eventos mais recentes são: 

Há 2 diasMESA | Devido a desarquivamento desta proposição em requerimento anterior, foi declarada prejudicada a solicitação de desarquiv...

Há 2 diasMESA | Devido a desarquivamento desta proposição em requerimento anterior, foi declarada prejudicada a solicitação de desarquiv...

**Comment by tarcisocomp** [comment]
Na verdade esses eventos são diferentes, mas a parte do texto que os diferencia está no final, quando fazem referência ao requerimento que foi prejudicado. O número muda de um pra o outro. 

A idéia é basicamente que depois que um requerimento de desarquivamento foi aprovado, todos os outros são declarados prejudicados. Pelo visto, havia pelo menos 10 requerimentos de desarquivamento desse PL.
