### ISSUE TITLE
Na página detalhada da MPV da Liberdade Econômica, o gráfico da temperatura histórica tá bem pequeno comparado com o da pressão.

### ISSUE THREAD

**Issue by MatheusHALeal** [analytics-ufcg/leggo-frontend#369]
Na página detalhada da MPV da Liberdade Econômica, o gráfico da temperatura histórica tá bem pequeno comparado com o da pressão.

_Originally posted by @tarcisocomp in https://github.com/analytics-ufcg/leggo-frontend/pull/363#issuecomment-527225218_

**Comment by marcellasiqueira** [comment]
Já foi resolvido
