### ISSUE TITLE
Error 404 ao clicar no tipo de títulos na tabela de análise de emendas

### ISSUE THREAD

**Issue by ivynasantino** [analytics-ufcg/leggo-frontend#376]
Ao clicar em EMC 16 por exemplo, redireciona para uma página, acredito que seria a que contém o documento, no entanto como resposta tenho Error 404.

![image](https://user-images.githubusercontent.com/18709508/64631775-293b8100-d3ce-11e9-8384-33316f0b25da.png)

**Comment by augusto-herrmann** [comment]
Também observei esse problema. Ocorre em todas as emendas.

**Comment by ivynasantino** [comment]
Obg pela observação @augusto-herrmann :). Estamos trabalhando nessa issue, e logo mais, os documentos estarão acessíveis novamente.

**Comment by ivynasantino** [comment]
Os documentos já estão disponíveis novamente @augusto-herrmann :)

**Comment by augusto-herrmann** [comment]
Excelente! :tada: 

Obrigado. :)
